### ISSUE TITLE
Bind-attr syntax

### ISSUE THREAD

**Issue by arthur5005** [joshforisha/ember-foundation#8]
Using this in anything above 1.10 gives deprecation warnings for the bind-attr syntax. Any plans to migrate?

**Comment by joshforisha** [comment]
Yes, I plan on updating to Ember CLI 0.2.7 (and Ember 1.12) in the next few days.

**Comment by joshforisha** [comment]
Scratch that, I went ahead and updated it just now. I didn't do too thorough testing, but 0.7.2 should correct most of the deprecations. I'll leave this open until I get some more feedback on the changes.

**Comment by arthur5005** [comment]
Wow.. thanks!

**Comment by arthur5005** [comment]
If you're looking for feedback still, the deprecation warnings are all gone. Thanks again.
